### ISSUE TITLE
[Help Wanted] can't use it with any browser

### ISSUE THREAD

**Issue by 0xD3x** [Implex-ltd/Engine#10]
2023/11/12 21:47:14 Downloading browsers...
2023/11/12 21:47:14 Downloaded browsers successfully

 ┌───────────────────────────────────────────────────┐
 │                   Fiber v2.49.2                   │
 │               http://127.0.0.1:1234               │
 │       (bound on host 0.0.0.0 and port 1234)       │
 │                                                   │
 │ Handlers ............. 3  Processes ........... 1 │
 │ Prefork ....... Disabled  PID ............. 31596 │
 └───────────────────────────────────────────────────┘

2023/11/12 21:47:14 worker exited with error: invalid character 'I' looking for beginning of value
2023/11/12 21:47:15 worker exited with error: invalid character 'I' looking for beginning of value
2023/11/12 21:47:16 worker exited with error: invalid character 'I' looking for beginning of value
2023/11/12 21:47:16 worker exited with error: invalid character 'I' looking for beginning of value
2023/11/12 21:47:16 worker exited with error: invalid character 'I' looking for beginning of value
2023/11/12 21:47:17 worker exited with error: invalid character 'I' looking for beginning of value
2023/11/12 21:47:17 worker exited with error: invalid character 'I' looking for beginning of value
2023/11/12 21:47:18 worker exited with error: invalid character 'I' looking for beginning of value
2023/11/12 21:47:18 worker exited with error: invalid character 'I' looking for beginning of value
2023/11/12 21:47:19 worker exited with error: invalid character 'I' looking for beginning of value
2023/11/12 21:47:19 worker exited with error: invalid character 'I' looking for beginning of value
2023/11/12 21:47:19 worker exited with error: invalid character 'I' looking for beginning of value
2023/11/12 21:47:20 worker exited with error: invalid character 'I' looking for beginning of value
2023/11/12 21:47:20 worker exited with error: invalid character 'I' looking for beginning of value
2023/11/12 21:47:21 worker exited with error: invalid character 'I' looking for beginning of value
2023/11/12 21:47:21 worker exited with error: invalid character 'I' looking for beginning of value
2023/11/12 21:47:22 worker exited with error: invalid character 'I' looking for beginning of value
2023/11/12 21:47:22 worker exited with error: invalid character 'I' looking for beginning of value
2023/11/12 21:47:22 worker exited with error: invalid character 'I' looking for beginning of value
2023/11/12 21:47:23 worker exited with error: invalid character 'I' looking for beginning of value
2023/11/12 21:47:23 worker exited with error: invalid character 'I' looking for beginning of value
2023/11/12 21:47:24 worker exited with error: invalid character 'I' looking for beginning of value
2023/11/12 21:47:25 worker exited with error: invalid character 'I' looking for beginning of value

**Comment by 0xF7A4C6** [comment]
You have to put apiKey
